Fix add_allowed not to add duplicates

diff --git a/cmds/add_allowed b/cmds/add_allowed
--- a/cmds/add_allowed
+++ b/cmds/add_allowed
@@ -1,20 +1,41 @@
 #!/bin/bash
 ###
 ### This script adds an address to the list of authorized addresses
+### Usage: add_allowed <address> [alias]
 ###
+### Example:
+### docker exec <container> add_allowed <node-address>
+### docker exec <container> add_allowed <node-address1> my-alias
+###
+
 FILE=/edge_node/_local_cache/authorized_addrs
 
 # Check if at least one argument is provided
 if [ $# -eq 0 ]; then
-  echo "Usage: $0 <address> [alias]"
+  echo "Usage: $0 <address> [alias]" >&2
+  exit 1
+fi
+
+address="$1"
+alias="$2"
+
+# Check if address already exists
+if grep -q "^$address\( \|$\)" "$FILE"; then
+  echo "Error: Address already exists: $address" >&2
+  exit 1
+fi
+
+# If alias is provided, check if it already exists
+if [ -n "$alias" ] && grep -q " $alias$" "$FILE"; then
+  echo "Error: Alias already exists: $alias" >&2
   exit 1
 fi
 
 # Append the address and optional alias as a new line at the end of the file
 if [ $# -eq 1 ]; then
-  echo "$1" >> "$FILE"
+  echo "$address" >> "$FILE"
 else
-  echo "$1  $2" >> "$FILE"
+  echo "$address  $alias" >> "$FILE"
 fi
 
 # sleep before calling get_node_info
