Add checks if file exists for CLI commands

diff --git a/cmds/get_allowed b/cmds/get_allowed
--- a/cmds/get_allowed
+++ b/cmds/get_allowed
@@ -4,4 +4,9 @@
 ###
 FILE=/edge_node/_local_cache/authorized_addrs
 
+if [ ! -f "$FILE" ]; then
+    echo "Error: $FILE does not exist"
+    exit 1
+fi
+
 cat $FILE
diff --git a/cmds/get_config_app b/cmds/get_config_app
--- a/cmds/get_config_app
+++ b/cmds/get_config_app
@@ -4,4 +4,9 @@
 ###
 FILE=/edge_node/_local_cache/_data/box_configuration/config_app.txt
 
+if [ ! -f "$FILE" ]; then
+    echo "Error: $FILE does not exist"
+    exit 1
+fi
+
 cat $FILE
diff --git a/cmds/get_startup_config b/cmds/get_startup_config
--- a/cmds/get_startup_config
+++ b/cmds/get_startup_config
@@ -4,4 +4,9 @@
 ###
 FILE=/edge_node/_local_cache/config_startup.json
 
+if [ ! -f "$FILE" ]; then
+    echo "Error: $FILE does not exist"
+    exit 1
+fi
+
 cat $FILE
